### ISSUE TITLE
WlanApi Full Implementation

### ISSUE THREAD

**Issue by ghost** [antoniotejada/WiFiDirectLegacyAP#1]
Please update your code to python 3 to make it relevant and clean your code. Specifically, create a soft AP using wlanapi. I'm also testing that but on my python 3 venv, thanks!

**Comment by antoniotejada** [comment]
> Please update your code to python 3 to make it relevant.

I don't care for Python 3 so that is not going to happen. I may take pull requests as long as they are Python 2.7 compatible.

> Specifically, create a soft AP using wlanapi.

What do you mean with that, writing the equivalent to WiFiDirectLegacyAP code but using wlanapi? As far as I know you cannot create a wifidirect access point with wlanapi, you can only create [hosted network access points](https://learn.microsoft.com/en-us/windows/win32/nativewifi/about-the-wireless-hosted-network), but those require hosted network hardware support that has been deprecated by Microsoft and removed by hardware vendors, so it's very unlikely your hardware will support it. See https://superuser.com/a/1590342

Why do you want wlanapi?

Closing wontfix since there's nothing actionable here.

**Comment by ghost** [comment]
Windows 10 has mobile hotspot supported and it works completely well even if the laptop/PC does not support hostednetwork. Given that, my goal is to have full control over the mobile hotspot feature including the DOT11_AUTH and the DOT11_CIPHER on a security setting I want. How's this possible?

**Comment by antoniotejada** [comment]
> Windows 10 has mobile hotspot supported and it works completely well even if the laptop/PC does not support hostednetwork. 

Right, nobody says Windows 10 mobile hotspot is implemented over hosted network hardware support, could be implemented over wifidirect using the same winrt APIs that WiFiDirectLegacyAP uses (not saying that it is, I don't know which API it's implemented on).
